---
- name: "PLAY 1: CONFIGURAR IPV6 EN ROUTER"
  hosts: csr_routers
  gather_facts: false

  tasks:
    - name: "TAREA 1: ASIGNAR DIRECCIONAMIENTO IPV6 A LOOPBACK 33"
      ios_config:
        lines:
          - description Interfaz para Examen Transversal
          - ipv6 address 3001:ABCD:ABCD:1::1/128
          - ipv6 address FE80::1 link-local
        parents: interface Loopback33
